#!/usr/bin/env python
# pyright: reportMissingImports=false, reportMissingModuleSource=false
"""
Placeholder manage.py generated by infra/setup-faithful-local.ps1.

Replace this with your real project entrypoint once the application code is available.
"""
from __future__ import annotations

import os
import sys
from typing import Sequence


def main(argv: Sequence[str] | None = None) -> None:
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tapne.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Django is not available. Install dependencies from requirements.txt first."
        ) from exc
    execute_from_command_line(list(argv or sys.argv))


if __name__ == "__main__":
    main()
