# Generated by Django 5.2.11 on 2026-02-10 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessageThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_threads_as_member_one",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_threads_as_member_two",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=4000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_direct_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="interactions.directmessagethread",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("trip", "Trip"), ("blog", "Blog")], max_length=12
                    ),
                ),
                ("target_key", models.CharField(max_length=191)),
                ("target_label", models.CharField(blank=True, max_length=255)),
                ("target_url", models.CharField(blank=True, max_length=255)),
                ("text", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="interactions.comment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_key", "parent", "created_at"],
                        name="interact_comment_target_idx",
                    ),
                    models.Index(
                        fields=["author", "created_at"],
                        name="interact_comment_author_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("pk", models.F("parent_id")), _negated=True
                        ),
                        name="interact_comment_no_self_parent",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="directmessagethread",
            index=models.Index(
                fields=["member_one", "updated_at"], name="interact_dm_one_upd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessagethread",
            index=models.Index(
                fields=["member_two", "updated_at"], name="interact_dm_two_upd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="directmessagethread",
            constraint=models.UniqueConstraint(
                fields=("member_one", "member_two"), name="interact_dm_unique_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="directmessagethread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("member_one", models.F("member_two")), _negated=True
                ),
                name="interact_dm_no_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="directmessagethread",
            constraint=models.CheckConstraint(
                condition=models.Q(("member_one__lt", models.F("member_two"))),
                name="interact_dm_pair_order",
            ),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["thread", "created_at"], name="interact_dmsg_thread_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="interact_dmsg_sender_idx"
            ),
        ),
    ]
