apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tapne-web
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: us-central1-docker.pkg.dev/PROJECT_ID/REPO/tapne-web:TAG
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: STORAGE_BACKEND
              value: "gcs"
            - name: GCS_BUCKET_NAME
              value: "REPLACE_WITH_BUCKET_NAME"
            - name: RUN_MIGRATIONS
              value: "false"
            - name: COLLECTSTATIC_ON_BOOT
              value: "false"
            - name: CANONICAL_SCHEME
              value: "https"
            - name: CANONICAL_HOST
              value: "REPLACE_WITH_CANONICAL_HOST"
            - name: CANONICAL_HOST_REDIRECT_ENABLED
              value: "true"
          startupProbe:
            httpGet:
              path: /runtime/health/
              port: 8080
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /runtime/health/
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
