# Generated by Django 5.2.11 on 2026-02-09 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("excerpt", models.CharField(blank=True, max_length=280)),
                ("body", models.TextField(blank=True)),
                ("reads", models.PositiveIntegerField(default=0)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_blogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["author", "created_at"], name="blog_author_created_idx"
                    ),
                    models.Index(
                        fields=["is_published", "created_at"],
                        name="blog_pub_created_idx",
                    ),
                    models.Index(fields=["reads", "id"], name="blog_reads_rank_idx"),
                ],
            },
        ),
    ]
