# Generated by Django 5.2.11 on 2026-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="cover_image_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="blog",
            name="location",
            field=models.CharField(blank=True, default="", max_length=180),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
