# Generated by Django 5.2.11 on 2026-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_cover_image_url_blog_location_blog_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
