# Generated by Django 5.2.11 on 2026-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
