# Generated by Django 5.2.13 on 2026-04-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='travel_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
