# Generated by Django 5.2.11 on 2026-02-11 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("value", models.BigIntegerField(default=0)),
                ("source", models.CharField(default="cache", max_length=24)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("key",),
                "indexes": [
                    models.Index(
                        fields=["source", "updated_at"],
                        name="runtime_counter_source_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="runtime_counter_expires_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RuntimeIdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_fingerprint", models.CharField(blank=True, max_length=64)),
                ("status_code", models.PositiveSmallIntegerField(default=202)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_idempotency_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["scope", "owner", "created_at"],
                        name="runtime_idem_scope_owner_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "created_at"],
                        name="runtime_idem_exp_created",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "idempotency_key"),
                        name="runtime_idem_scope_key_uq",
                    )
                ],
            },
        ),
    ]
