# Generated by Django 5.2.11 on 2026-02-10 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("trip", "Trip"), ("blog", "Blog")], max_length=12
                    ),
                ),
                ("target_key", models.CharField(max_length=191)),
                ("target_label", models.CharField(blank=True, max_length=255)),
                ("target_url", models.CharField(blank=True, max_length=255)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("headline", models.CharField(blank=True, max_length=160)),
                ("body", models.CharField(max_length=4000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_key", "created_at"],
                        name="reviews_target_created_idx",
                    ),
                    models.Index(
                        fields=["author", "created_at"],
                        name="reviews_author_created_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("author", "target_type", "target_key"),
                        name="reviews_unique_author_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="reviews_rating_between_1_5",
                    ),
                ],
            },
        ),
    ]
