# Generated by Django 5.2.11 on 2026-02-09 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("trip", "Trip"), ("user", "User"), ("blog", "Blog")],
                        max_length=12,
                    ),
                ),
                ("target_key", models.CharField(max_length=191)),
                ("target_label", models.CharField(blank=True, max_length=255)),
                ("target_url", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["member", "target_type", "created_at"],
                        name="social_bookmark_mt_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_key"],
                        name="social_bookmark_lookup_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "target_type", "target_key"),
                        name="social_unique_bookmark",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FollowRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["follower", "created_at"], name="social_follow_out_idx"
                    ),
                    models.Index(
                        fields=["following", "created_at"], name="social_follow_in_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "following"), name="social_unique_follow"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("follower", models.F("following")), _negated=True
                        ),
                        name="social_no_self_follow",
                    ),
                ],
            },
        ),
    ]
