# Generated by Django 5.2.11 on 2026-02-10 22:36

import django.db.models.deletion
import media.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=media.models.media_upload_to)),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=12
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=127)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("width_px", models.PositiveIntegerField(blank=True, null=True)),
                ("height_px", models.PositiveIntegerField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="MediaAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("trip", "Trip"),
                            ("blog", "Blog"),
                            ("review", "Review"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_key", models.CharField(max_length=191)),
                ("target_label", models.CharField(blank=True, max_length=255)),
                ("target_url", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["owner", "created_at"], name="media_asset_owner_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["kind", "created_at"], name="media_asset_kind_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaattachment",
            index=models.Index(
                fields=["target_type", "target_key", "created_at"],
                name="media_target_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaattachment",
            index=models.Index(
                fields=["asset", "created_at"], name="media_asset_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaattachment",
            constraint=models.UniqueConstraint(
                fields=("asset", "target_type", "target_key"),
                name="media_unique_asset_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_type__in", ("trip", "blog", "review"))),
                name="media_attachment_target_type_allowed",
            ),
        ),
    ]
