# Generated by Django 5.2.11 on 2026-02-08 20:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("summary", models.CharField(blank=True, max_length=280)),
                ("description", models.TextField(blank=True)),
                ("destination", models.CharField(blank=True, max_length=160)),
                (
                    "starts_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("traffic_score", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["host", "starts_at"], name="trip_host_start_idx"
                    ),
                    models.Index(
                        fields=["is_published", "starts_at"], name="trip_pub_start_idx"
                    ),
                ],
            },
        ),
    ]
