# Generated by Django 5.2.11 on 2026-02-15 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="budget_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("budget", "$ Budget-friendly"),
                    ("mid", "$$ Mid-range"),
                    ("premium", "$$$ Premium"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easy", "Easy"),
                    ("moderate", "Moderate"),
                    ("challenging", "Challenging"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="group_size_label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4-6 travelers", "4-6 travelers"),
                    ("6-8 travelers", "6-8 travelers"),
                    ("6-10 travelers", "6-10 travelers"),
                    ("8-12 travelers", "8-12 travelers"),
                    ("10-14 travelers", "10-14 travelers"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="includes_label",
            field=models.CharField(blank=True, default="", max_length=280),
        ),
        migrations.AddField(
            model_name="trip",
            name="pace_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("relaxed", "Relaxed"),
                    ("balanced", "Balanced"),
                    ("fast", "Fast-paced"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("food-culture", "Food & Culture"),
                    ("trekking", "Trekking"),
                    ("desert", "Desert Route"),
                    ("city", "City Discovery"),
                    ("coastal", "Coastal Escape"),
                    ("adventure", "Adventure"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(4000)]
            ),
        ),
    ]
