# Generated by Django 5.2.11 on 2026-02-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_budget_tier_trip_difficulty_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="banner_image",
            field=models.ImageField(blank=True, upload_to="trip_banners/"),
        ),
    ]
