# Generated by Django 5.2.11 on 2026-02-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="age_preference",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="trip",
            name="approximate_flight_cost",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="trip",
            name="booking_closes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="buffer_budget_suggestion",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="trip",
            name="cancellation_policy",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="trip",
            name="co_hosts",
            field=models.CharField(blank=True, default="", max_length=280),
        ),
        migrations.AddField(
            model_name="trip",
            name="code_of_conduct",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="trip",
            name="contact_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in_app", "In-app messages"),
                    ("email", "Email"),
                    ("phone", "Phone call"),
                    ("whatsapp", "WhatsApp"),
                ],
                default="in_app",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="cost_breakdown_accommodation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="cost_breakdown_activities",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="cost_breakdown_guide",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="cost_breakdown_miscellaneous",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="cost_breakdown_transportation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="currency",
            field=models.CharField(blank=True, default="INR", max_length=8),
        ),
        migrations.AddField(
            model_name="trip",
            name="early_bird_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="emergency_contact_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="experience_level_required",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="extra_costs_not_included",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trip",
            name="faqs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trip",
            name="fitness_level_required",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High")],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="gender_preference",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="trip",
            name="has_early_bird_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="highlights",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trip",
            name="included_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trip",
            name="itinerary_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trip",
            name="medical_declaration_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="minimum_seats",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="not_included_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trip",
            name="optional_activities_cost",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="trip",
            name="payment_terms",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="trip",
            name="personal_shopping_estimate",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="trip",
            name="price_per_person",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="suitable_for",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trip",
            name="things_to_carry",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_seats",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_trip_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_vibe",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trip",
            name="video_link",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
