# Generated by Codex on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_trip_age_preference_trip_approximate_flight_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="general_policies",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="trip",
            name="contact_preference",
            field=models.CharField(blank=True, default="in_app", max_length=280),
        ),
    ]
