# Generated by Django 5.2.11 on 2026-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_trip_general_policies_and_contact_preference_multi"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="access_type",
            field=models.CharField(blank=True, default="open", max_length=16),
        ),
        migrations.AddField(
            model_name="trip",
            name="draft_form_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="trip",
            name="payment_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="trip",
            name="payment_method",
            field=models.CharField(blank=True, default="direct_contact", max_length=32),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("city", "City Break"),
                    ("culture-heritage", "Culture & Heritage"),
                    ("food-culture", "Food & Culinary"),
                    ("trekking", "Trekking & Hiking"),
                    ("coastal", "Beach & Coastal"),
                    ("desert", "Desert Expedition"),
                    ("wildlife", "Wildlife & Safari"),
                    ("road-trip", "Road Trip"),
                    ("camping", "Camping"),
                    ("wellness", "Wellness Retreat"),
                    ("adventure-sports", "Adventure Sports"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
