# Generated by Django 5.2.11 on 2026-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_trip_status_review_prompts_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
