# Generated by Django 5.2.12 on 2026-04-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('city', 'City Break'), ('culture-heritage', 'Culture & Heritage'), ('food-culture', 'Food & Culinary'), ('trekking', 'Trekking & Hiking'), ('coastal', 'Beach & Coastal'), ('desert', 'Desert Expedition'), ('wildlife', 'Wildlife & Safari'), ('road-trip', 'Road Trip'), ('camping', 'Camping'), ('wellness', 'Wellness Retreat'), ('adventure-sports', 'Adventure Sports')], default='', max_length=24),
        ),
    ]
