# Generated by Django 5.2.11 on 2026-04-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_trip_status_review_prompts_sent"),
        ("trips", "0009_alter_trip_trip_type"),
    ]

    operations = []
