# Generated by Django 5.2.11 on 2026-02-10 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_updates",
                    models.CharField(
                        choices=[
                            ("all", "All activity"),
                            ("important", "Only important updates"),
                            ("none", "No email updates"),
                        ],
                        default="important",
                        max_length=16,
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("members", "Members only")],
                        default="public",
                        max_length=16,
                    ),
                ),
                (
                    "dm_privacy",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("following", "People you follow"),
                            ("none", "No one"),
                        ],
                        default="following",
                        max_length=16,
                    ),
                ),
                (
                    "search_visibility",
                    models.BooleanField(
                        default=True,
                        help_text="When false, this profile is de-prioritized from discovery surfaces.",
                    ),
                ),
                (
                    "digest_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When true, member activity digest emails can be sent.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tapne_member_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["email_updates", "updated_at"],
                        name="settings_email_updated_idx",
                    ),
                    models.Index(
                        fields=["profile_visibility", "updated_at"],
                        name="settings_visibility_idx",
                    ),
                    models.Index(
                        fields=["dm_privacy", "updated_at"],
                        name="settings_dm_privacy_idx",
                    ),
                ],
            },
        ),
    ]
