# Generated by Django 5.2.11 on 2026-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersettings",
            name="color_scheme",
            field=models.CharField(
                choices=[("soft_teal", "Soft teal")],
                default="soft_teal",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="membersettings",
            name="theme_preference",
            field=models.CharField(
                choices=[
                    ("system", "Follow system"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                ],
                default="system",
                max_length=16,
            ),
        ),
    ]
