# Generated by Django 5.2.11 on 2026-02-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0002_membersettings_color_scheme_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membersettings",
            name="color_scheme",
        ),
    ]

